name: CI Tests
on: [push, pull_request]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Build tests
      run: cargo test --verbose --no-run

    - name: Run tests
      run: cargo test --verbose --no-fail-fast -- --test-threads=1